// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Models;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20231002145501_init4")]
    partial class init4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.AgeGroups", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AgeGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Noworodek"
                        },
                        new
                        {
                            Id = 2,
                            Name = "2 miesiąc życia"
                        },
                        new
                        {
                            Id = 3,
                            Name = "3-4 miesiąc życia"
                        },
                        new
                        {
                            Id = 4,
                            Name = "5-6 miesiąc życia"
                        },
                        new
                        {
                            Id = 5,
                            Name = "7 miesiąc życia"
                        },
                        new
                        {
                            Id = 6,
                            Name = "13-14 miesiąc życia"
                        },
                        new
                        {
                            Id = 7,
                            Name = "16-18 miesiąc życia"
                        },
                        new
                        {
                            Id = 8,
                            Name = "6 rok życia"
                        },
                        new
                        {
                            Id = 9,
                            Name = "10 rok życia"
                        },
                        new
                        {
                            Id = 10,
                            Name = "14 rok życia"
                        },
                        new
                        {
                            Id = 11,
                            Name = "19 rok życia"
                        });
                });

            modelBuilder.Entity("backend.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PESEL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("backend.Models.TypesVaccines", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypesVaccines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gruźlica BCG"
                        },
                        new
                        {
                            Id = 2,
                            Name = "wzw B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "DTP"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hib"
                        },
                        new
                        {
                            Id = 5,
                            Name = "polio IPV"
                        },
                        new
                        {
                            Id = 6,
                            Name = "odra, świnka, różyczka"
                        },
                        new
                        {
                            Id = 7,
                            Name = "DTaP"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Td"
                        });
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("backend.Models.VaccinationSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgeGroupsId")
                        .HasColumnType("int");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdAgeGroups")
                        .HasColumnType("int");

                    b.Property<int>("IdTypesVaccines")
                        .HasColumnType("int");

                    b.Property<int?>("TypesVaccinesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgeGroupsId");

                    b.HasIndex("IdAgeGroups");

                    b.HasIndex("IdTypesVaccines");

                    b.HasIndex("TypesVaccinesId");

                    b.ToTable("VaccinationSchedules");
                });

            modelBuilder.Entity("backend.Models.VaccinationSchedule", b =>
                {
                    b.HasOne("backend.Models.AgeGroups", null)
                        .WithMany("VaccinationSchedules")
                        .HasForeignKey("AgeGroupsId");

                    b.HasOne("backend.Models.AgeGroups", "AgeGroups")
                        .WithMany()
                        .HasForeignKey("IdAgeGroups")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.TypesVaccines", "TypesVaccines")
                        .WithMany()
                        .HasForeignKey("IdTypesVaccines")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.TypesVaccines", null)
                        .WithMany("VaccinationSchedules")
                        .HasForeignKey("TypesVaccinesId");

                    b.Navigation("AgeGroups");

                    b.Navigation("TypesVaccines");
                });

            modelBuilder.Entity("backend.Models.AgeGroups", b =>
                {
                    b.Navigation("VaccinationSchedules");
                });

            modelBuilder.Entity("backend.Models.TypesVaccines", b =>
                {
                    b.Navigation("VaccinationSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
