// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Database;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20231008214636_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Entities.AgeGroups", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AgeGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Noworodek"
                        },
                        new
                        {
                            Id = 2,
                            Name = "2 miesiąc życia"
                        },
                        new
                        {
                            Id = 3,
                            Name = "3-4 miesiąc życia"
                        },
                        new
                        {
                            Id = 4,
                            Name = "5-6 miesiąc życia"
                        },
                        new
                        {
                            Id = 5,
                            Name = "7 miesiąc życia"
                        },
                        new
                        {
                            Id = 6,
                            Name = "13-14 miesiąc życia"
                        },
                        new
                        {
                            Id = 7,
                            Name = "16-18 miesiąc życia"
                        },
                        new
                        {
                            Id = 8,
                            Name = "6 rok życia"
                        },
                        new
                        {
                            Id = 9,
                            Name = "10 rok życia"
                        },
                        new
                        {
                            Id = 10,
                            Name = "14 rok życia"
                        },
                        new
                        {
                            Id = 11,
                            Name = "19 rok życia"
                        });
                });

            modelBuilder.Entity("backend.Entities.Babysitter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FisrtName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kinship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PESEL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Babysitters");
                });

            modelBuilder.Entity("backend.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BabysitterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfAbandonment")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfDeclaration")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PESEL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeOfVaccination")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BabysitterId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("backend.Entities.Summons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avoid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Send")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Summons");
                });

            modelBuilder.Entity("backend.Entities.TypesVaccines", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypesVaccines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gruźlica BCG"
                        },
                        new
                        {
                            Id = 2,
                            Name = "wzw B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "DTP"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hib"
                        },
                        new
                        {
                            Id = 5,
                            Name = "polio IPV"
                        },
                        new
                        {
                            Id = 6,
                            Name = "odra, świnka, różyczka"
                        },
                        new
                        {
                            Id = 7,
                            Name = "DTaP"
                        },
                        new
                        {
                            Id = 8,
                            Name = "polio OPV"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Td"
                        });
                });

            modelBuilder.Entity("backend.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("backend.Entities.VaccinationCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Emigration")
                        .HasColumnType("bit");

                    b.Property<bool>("Lack")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Received")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Send")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("VaccinationCard");
                });

            modelBuilder.Entity("backend.Entities.VaccinationInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Appointment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCaccinationReaction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postponement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostponementOfCaccination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VaccinationInfo");
                });

            modelBuilder.Entity("backend.Entities.VaccinationSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeGroupsId")
                        .HasColumnType("int");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypesVaccinesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgeGroupsId");

                    b.HasIndex("TypesVaccinesId");

                    b.ToTable("VaccinationSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeGroupsId = 1,
                            Dose = "",
                            TypesVaccinesId = 1
                        },
                        new
                        {
                            Id = 2,
                            AgeGroupsId = 1,
                            Dose = "1",
                            TypesVaccinesId = 2
                        },
                        new
                        {
                            Id = 3,
                            AgeGroupsId = 2,
                            Dose = "2",
                            TypesVaccinesId = 2
                        },
                        new
                        {
                            Id = 4,
                            AgeGroupsId = 2,
                            Dose = "1",
                            TypesVaccinesId = 3
                        },
                        new
                        {
                            Id = 5,
                            AgeGroupsId = 2,
                            Dose = "1",
                            TypesVaccinesId = 4
                        },
                        new
                        {
                            Id = 6,
                            AgeGroupsId = 3,
                            Dose = "2",
                            TypesVaccinesId = 3
                        },
                        new
                        {
                            Id = 7,
                            AgeGroupsId = 3,
                            Dose = "2",
                            TypesVaccinesId = 4
                        },
                        new
                        {
                            Id = 8,
                            AgeGroupsId = 3,
                            Dose = "1",
                            TypesVaccinesId = 5
                        },
                        new
                        {
                            Id = 9,
                            AgeGroupsId = 4,
                            Dose = "3",
                            TypesVaccinesId = 3
                        },
                        new
                        {
                            Id = 10,
                            AgeGroupsId = 4,
                            Dose = "3",
                            TypesVaccinesId = 4
                        },
                        new
                        {
                            Id = 11,
                            AgeGroupsId = 4,
                            Dose = "2",
                            TypesVaccinesId = 5
                        },
                        new
                        {
                            Id = 12,
                            AgeGroupsId = 5,
                            Dose = "3",
                            TypesVaccinesId = 2
                        },
                        new
                        {
                            Id = 13,
                            AgeGroupsId = 6,
                            Dose = "1",
                            TypesVaccinesId = 6
                        },
                        new
                        {
                            Id = 14,
                            AgeGroupsId = 7,
                            Dose = "4",
                            TypesVaccinesId = 3
                        },
                        new
                        {
                            Id = 15,
                            AgeGroupsId = 7,
                            Dose = "3",
                            TypesVaccinesId = 5
                        },
                        new
                        {
                            Id = 16,
                            AgeGroupsId = 7,
                            Dose = "4",
                            TypesVaccinesId = 4
                        },
                        new
                        {
                            Id = 17,
                            AgeGroupsId = 8,
                            Dose = "1 dawka przypominająca",
                            TypesVaccinesId = 7
                        },
                        new
                        {
                            Id = 18,
                            AgeGroupsId = 8,
                            Dose = "",
                            TypesVaccinesId = 8
                        },
                        new
                        {
                            Id = 19,
                            AgeGroupsId = 9,
                            Dose = "2 dawka przypominająca",
                            TypesVaccinesId = 6
                        },
                        new
                        {
                            Id = 20,
                            AgeGroupsId = 10,
                            Dose = "2 dawka przypominająca",
                            TypesVaccinesId = 9
                        },
                        new
                        {
                            Id = 21,
                            AgeGroupsId = 11,
                            Dose = "3 dawka przypominająca",
                            TypesVaccinesId = 9
                        });
                });

            modelBuilder.Entity("backend.Entities.Vaccinations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfProduction")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vaccinations");
                });

            modelBuilder.Entity("backend.Entities.Patient", b =>
                {
                    b.HasOne("backend.Entities.Babysitter", "Babysitter")
                        .WithMany("Patient")
                        .HasForeignKey("BabysitterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Babysitter");
                });

            modelBuilder.Entity("backend.Entities.Summons", b =>
                {
                    b.HasOne("backend.Entities.Patient", "Patient")
                        .WithMany("Summons")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("backend.Entities.VaccinationCard", b =>
                {
                    b.HasOne("backend.Entities.Patient", "Patient")
                        .WithOne("VaccinationCard")
                        .HasForeignKey("backend.Entities.VaccinationCard", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("backend.Entities.VaccinationSchedule", b =>
                {
                    b.HasOne("backend.Entities.AgeGroups", "AgeGroups")
                        .WithMany("VaccinationSchedules")
                        .HasForeignKey("AgeGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.TypesVaccines", "TypesVaccines")
                        .WithMany("VaccinationSchedules")
                        .HasForeignKey("TypesVaccinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgeGroups");

                    b.Navigation("TypesVaccines");
                });

            modelBuilder.Entity("backend.Entities.AgeGroups", b =>
                {
                    b.Navigation("VaccinationSchedules");
                });

            modelBuilder.Entity("backend.Entities.Babysitter", b =>
                {
                    b.Navigation("Patient");
                });

            modelBuilder.Entity("backend.Entities.Patient", b =>
                {
                    b.Navigation("Summons");

                    b.Navigation("VaccinationCard");
                });

            modelBuilder.Entity("backend.Entities.TypesVaccines", b =>
                {
                    b.Navigation("VaccinationSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
